(* ::Package:: *)

(* ::Text:: *)
(*Problem 1: y^\[Prime]\[Prime]+x Derivative[1][y]+y==2+3 x^2*)


(* ::Input:: *)
(*(*Clear previous variables*)*)
(*Clear[x,y,y1,y2,v1,v2,w,f,yh,yc,yp,sol]*)
(*(*Define the equations*)*)
(*eq1=y''[x]+x*y'[x]+y[x]==3*x^2+2;*)
(*(*Nonhomogeneous*)eq0=y''[x]+x*y'[x]+y[x]==0;*)
(*(*Homogeneous*)f[x_]=3*x^2+2;(*RHS function*)*)
(*Print["Nonhomogeneous eq: ",eq1];*)
(*Print["Homogeneous eq: ",eq0];*)
(*Print["RHS function f(x): ",f[x]];*)
(*(*Solve homogeneous equation*)*)
(*yh=DSolve[eq0,y[x],x][[1]];*)
(*Print["Homogeneous solution yh: ",yh];*)
(*(*Define two independent solutions*)*)
(*y1[x_]=y[x]/.yh/.{C[1]->1,C[2]->0};*)
(*y2[x_]=y[x]/.yh/.{C[1]->0,C[2]->1};*)
(*Print["Independent solution y1(x): ",y1[x]];*)
(*Print["Independent solution y2(x): ",y2[x]];*)
(*(*Wronskian*)*)
(*w=Det[{{y1[x],y2[x]},{y1'[x],y2'[x]}}];*)
(*Print["Wronskian w(x): ",w];*)
(*(*Variation of parameters:compute v1 and v2*)*)
(*v1=-Integrate[y2[x]*f[x]/w,x];*)
(*v2=Integrate[y1[x]*f[x]/w,x];*)
(*Print["v1(x) = ",v1];*)
(*Print["v2(x) = ",v2];*)
(*(*Particular solution*)*)
(*yp=v1*y1[x]+v2*y2[x];*)
(*Print["Particular solution yp(x): ",yp];*)
(*(*Complementary (homogeneous) solution*)*)
(*yc=y[x]/.yh;*)
(*Print["Complementary solution yc(x): ",yc];*)
(*(*General solution*)*)
(*sol[x_]=Simplify[yc+yp];*)
(*Print["General solution sol(x): ",sol[x]];*)


(* ::Text:: *)
(*Problem 2: y^\[Prime]\[Prime]+4y==sin(x)*)


(* ::Input:: *)
(*(*Clear previous variables*)*)
(*Clear[x,y,y1,y2,v1,v2,w,f,yh,yc,yp,sol]*)
(*(*Define the equations*)*)
(*eq1=y''[x]+4*y[x]==Sin[x];*)
(*(*Nonhomogeneous*)eq0=y''[x]+4*y[x]==0;*)
(*(*Homogeneous*)*)
(*f[x_]=Sin[x];(*RHS function*)*)
(*Print["Nonhomogeneous eq: ",eq1];*)
(*Print["Homogeneous eq: ",eq0];*)
(*Print["RHS function f(x): ",f[x]];*)
(*(*Solve homogeneous equation*)*)
(*yh=DSolve[eq0,y[x],x][[1]];*)
(*Print["Homogeneous solution yh: ",yh];*)
(*(*Define two independent solutions*)*)
(*y1[x_]=y[x]/.yh/.{C[1]->1,C[2]->0};*)
(*y2[x_]=y[x]/.yh/.{C[1]->0,C[2]->1};*)
(*Print["Independent solution y1(x): ",y1[x]];*)
(*Print["Independent solution y2(x): ",y2[x]];*)
(*(*Wronskian*)*)
(*w=Det[{{y1[x],y2[x]},{y1'[x],y2'[x]}}];*)
(*Print["Wronskian w(x): ",w];*)
(*(*Variation of parameters:compute v1 and v2*)*)
(*v1=-Integrate[y2[x]*f[x]/w,x];*)
(*v2=Integrate[y1[x]*f[x]/w,x];*)
(*Print["v1(x) = ",v1];*)
(*Print["v2(x) = ",v2];*)
(*(*Particular solution*)*)
(*yp=v1*y1[x]+v2*y2[x];*)
(*Print["Particular solution yp(x): ",yp];*)
(*(*Complementary (homogeneous) solution*)*)
(*yc=y[x]/.yh;*)
(*Print["Complementary solution yc(x): ",yc];*)
(*(*General solution*)*)
(*sol[x_]=Simplify[yc+yp];*)
(*Print["General solution sol(x): ",sol[x]];*)



